Add .markdownlintignore file association
DavidAnson/vscode-markdownlint pull request #275
Opened 2023-02-04 11:29 UTC by thernstig

This makes sure that .markdownlintignore files are parsed as using ignore syntax.

Fixes #274

2023-02-04 17:37 UTC, DavidAnson requested changes
Looks good, thank you! Please update PR to be for "next" branch.

2023-02-05 22:44 UTC, DavidAnson commented
Also, I don't see "ignore" listed as a known language identifier, can you verify your change behaves as expected on a default install of VS Code?
<https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers>

2023-02-06 10:39 UTC, thernstig commented
@DavidAnson if you select the command `Select Language Mode` within VS Code you will see `ignore` is a valid option. I also added such things previously directly to the VS Code repository, see https://github.com/microsoft/vscode/pull/92397/files

So it is a bug in the VS Code docs.

2023-02-06 17:24 UTC, DavidAnson commented
That makes sense, thank you! I will accept this PR after I have a chance to try it.

2023-02-07 04:45 UTC, DavidAnson approved these changes

2023-02-07 04:47 UTC, merged